name: xeus-lite-dev
channels:
  - conda-forge
dependencies:
  - black
  - python-build
  - empack >=3.3
  - hatch-jupyter-builder
  - hatch-nodejs-version
  - jupyterlab >=4.0
  - jupyterlite-core
  - mamba <2
  - nodejs
  - pip
  - pytest
  - python
  - requests
  - ruff
  - traitlets
  - typer
  - yarn=3
