name: xeus-python-kernel-docs

channels:
  - conda-forge
  - conda-forge/label/jupyterlite_core_alpha

dependencies:
  - micromamba=2.0.5
  - pip
  - nodejs=20
  - click
  - typer
  - linkify-it-py
  - myst-parser
  - sphinx-design
  - pydata-sphinx-theme
  - jupyterlite-sphinx >=0.13.1
  - empack >=3.1.0
  - pip:
    - jupyterlab >=4.4.0.b0,<5
    - jupyterlite-core >=0.6.0.a8,<0.7
    - ..
