name: xeus-python-kernel-docs

channels:
  - conda-forge
  - conda-forge/label/jupyterlite_core_alpha

dependencies:
  - micromamba
  - pip
  - nodejs=20
  - click
  - typer
  - linkify-it-py
  - myst-parser
  - pydata-sphinx-theme
  - jupyterlab >=4.0.5,<5
  - jupyterlite-core >=0.2,<0.5
  - jupyterlite-sphinx >=0.13.1
  - empack >=3.1.0
  - pip:
    - ..
