name: xeus-python-kernel-docs
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - pillow
  - ipywidgets>=8.1.3
  - ipyleaflet
  - pip:
    - ipycanvas
